load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "matchers_intro",
    size = "small",
    srcs = ["matchers_intro.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "comparison",
    size = "small",
    srcs = ["comparison.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "optional",
    size = "small",
    srcs = ["optional.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "strings",
    size = "small",
    srcs = ["strings.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "composite",
    size = "small",
    srcs = ["composite.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "container",
    size = "small",
    srcs = ["container.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "member",
    size = "small",
    srcs = ["member.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "pointer",
    size = "small",
    srcs = ["pointer.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "predicates",
    size = "small",
    srcs = ["predicates.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "custom_matchers",
    size = "small",
    srcs = ["custom_matchers.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)