load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "BankServerLib",
    hdrs = [
        "atm_machine.h",
        "atm_machine_template.h",        
        "bankserver.h",
    ],
    visibility = ["//visibility:public"],
)
